pull_request_rules:
  - name: Automatic merge scala-steward changes with green CI 💚
    conditions:
        - author=scala-steward
        - check-success="Test / Run tests (pull_request)"
    actions:
      merge:
        method: merge
